menu:
  Home: /
  Archives: /archives
  # Tags: /tags

# duoshuo comment
duoshuo: true
duoshuo_name: makeup1122 

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: 
